import turtle

def bmw(t):
	t.fillcolor('black')
	t.begin_fill()
	t.circle(60)
	t.end_fill()
	t.penup()
	t.color('white')
	t.left(90)
	t.forward(20)
	t.right(90)
	t.pendown()
	t.fillcolor('dodger blue')
	t.begin_fill()
	t.circle(40)
	t.end_fill()
	t.color('black')
	t.left(90)
	t.forward(80)
	t.backward(40)
	t.right(90)
	t.forward(40)
	t.backward(80)
	t.forward(40)
	t.fillcolor('white')
	t.begin_fill()
	t.circle(40, 90)
	t.end_fill()